version: '3'
services:
 web:
   container_name: web
   build: .
#    command: bash -l
   volumes:
     - .:/workspace
   ports:
     - 3000:3000
   depends_on:
     - db
   tty: true
   stdin_open: true
 db:
   container_name: db
   image: mysql:5.7
   ports:
     - 3306:3306
   volumes:
     - ./vm/db/data:/var/lib/mysql
     - ./vm/db/init:/docker-entrypoint-initdb.d
   environment:
     MYSQL_ROOT_PASSWORD: password
     MYSQL_USER: railsuser
     MYSQL_PASSWORD: Railspass1!
